config/routes.rb
Superscription::Application.routes.draw do

  root :to => "static_pages#home"

  get :read, :to => "subscriptions#main"

  devise_for :users
  post :guest, :to => "guest_users#create"

  resources :users, :only => [] do
    resources :subscriptions, :only => [:index, :new]
  end

  resources :subscriptions, :only => [:create, :show]

  get :categories, :to => "categories#manage"

  namespace "api", :defaults => { :format => :json } do
    resources :user_subscriptions, :only => [:destroy]
    post "/user_subscriptions/:id/change_category", :to => "user_subscriptions#change_category"
    resources :readings, :only => [:create]
    resources :categories, :only => [:create, :destroy]
  end

end

app/models/subscription.rb
require 'open-uri'
require 'nokogiri'

class Subscription < ActiveRecord::Base
  attr_accessible :url, :title, :update_frequency, :last_build_date, :last_checked_at, :user_subscriptions_attributes

  validates :url, :title, :update_frequency, :last_checked_at, :presence => true

  has_many :user_subscriptions, :inverse_of => :subscription
  has_many :subscribers, :through => :user_subscriptions, :source => :user
  has_many :entries, :dependent => :destroy

  accepts_nested_attributes_for :user_subscriptions

  cattr_accessor :default_update_frequency
  @@default_update_frequency = 600

  def parsed_feed
    @parsed_feed ||= fetch_feed
  end

  def fetch_feed
    raw_feed = open(self.url)
    puts "Fetching feed ..."
    parsed_feed = Nokogiri::XML(raw_feed)
    puts "Got and parsed feed!"
    parsed_feed
  end

  def load_everything!
    load_info!
    load_entries!
  end

  def set_default_info
    self.title = self.url
    self.update_frequency = @@default_update_frequency
    self.last_build_date = DateTime.now
    # ludicrous date ensures that due_for_update? == true
    self.last_checked_at = 50.years.ago
  end

  def load_info!
    feed = self.parsed_feed
    self.title = feed.xpath('//title').first.text
    update_frequency_unit = feed.xpath('//sy:updatePeriod', "sy" => "http://purl.org/rss/1.0/modules/syndication/").text
    update_frequency = feed.xpath('//sy:updateFrequency', "sy" => "http://purl.org/rss/1.0/modules/syndication/").text.to_i
    if update_frequency != 0
      self.update_frequency = update_frequency_in_seconds(update_frequency_unit, update_frequency)
    else
      self.update_frequency = @@default_update_frequency
    end
  end

  def load_entries!
    feed = self.parsed_feed
    self.last_build_date = feed.xpath('//lastBuildDate').text.to_datetime
    self.last_checked_at = DateTime.now
    self.save
    entries = []
    feed.xpath('//item').each do |item|
      item_attributes = {:title => item.xpath('title').text,
       :author => item.xpath('dc:creator', "dc" => "http://purl.org/dc/elements/1.1/").text,
       :url => item.xpath('link').text,
       :datetime => item.xpath('pubDate').text.to_datetime ||
                     item.xpath('dc:date', "dc" => "http://purl.org/dc/elements/1.1/").text.to_datetime,
       :description => item.xpath('description').text,
       :content => item.xpath('content:encoded', "content" => "http://purl.org/rss/1.0/modules/content/").text,
       :guid => item.xpath('guid').text,
       :subscription_id => self.id}
      item_attributes.reject! { |key, value| value.is_a?(String) and value.empty? }
      entries.push(item_attributes)
      puts "Parsed attributes!"
    end
    entries.each do |entry_attributes|
      unless Entry.exists?(:guid => entry_attributes[:guid])
        Entry.create(entry_attributes)
        puts "Saved item!"
      else
        puts "Item already exists!"
      end
    end
  end

  def update_frequency_in_seconds(frequency_units, frequency_in_units)
    unit_in_seconds = { 'hourly' => 3600, 'daily' => 86400, 'weekly' => 604800,
      'monthly' => 2419200, 'yearly' => 31449600}
    unit_in_seconds[frequency_units] / frequency_in_units
  end

  def next_update_expected_at
    self.last_checked_at + self.update_frequency
  end

  def due_for_update?
    next_update_expected_at < DateTime.now
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_filter :authenticate_user!

  def main
    @user_subscriptions = current_user.user_subscriptions
    @categories = current_user.categories
    @category_entries = ActiveSupport::OrderedHash.new
    @categories.includes(:user_subscriptions).each do |category|
      @category_entries[category.name] = []
      category.user_subscriptions.each do |user_subscription|
        @category_entries[category.name] += user_subscription.unread_entries.to_a
      end
      @category_entries[category.name].sort_by! { |entry| entry.datetime }.reverse!
    end
    render :main
  end

  def index
    @user_subscriptions = UserSubscription.includes(:subscription).includes(:category).find_all_by_user_id(current_user.id)
    @user_subscriptions.sort_by! { |user_subscription| user_subscription.title }
    render :index
  end

  def show
    @subscription = Subscription.find(params[:id])
    @entries = @subscription.entries
    @entries.sort_by!{ |entry| entry.datetime }.reverse!
    render :show
  end

  def new
    @subscription = Subscription.new
    if current_user.categories.empty?
      current_user.categories.create(:name => "Uncategorized")
    end
    @categories = current_user.categories
    render :new
  end

  def create
    subscription_params = params[:subscription]
    subscription_params[:user_subscriptions_attributes][0][:user_id] = current_user.id

    # If another user has already subscribed to the same feed, use that and
    # just create a UserSubscription join model
    puts "using already stored feed!"
    existing_subscription = Subscription.find_by_url(params[:subscription][:url])
    if existing_subscription
      subscription_params[:user_subscriptions_attributes][0][:subscription_id] = existing_subscription.id
      user_subscription = UserSubscription.new(subscription_params[:user_subscriptions_attributes][0])
      if user_subscription.save
        redirect_to user_subscriptions_url(current_user)
        return
      else
        flash.now[:alert] = "Something went wrong! Couldn't save subscription."
        @subscription = Subscription.new
        @categories = current_user.categories
        render :new
        return
      end
    end

    # Otherwise, create a new Subscription (which accepts_nested_attributes_for
    # a UserSubscription)
    @subscription = Subscription.new(subscription_params)
    begin
      @subscription.load_everything!
    rescue NoMethodError, Errno::ENOENT
      @categories = current_user.categories
      flash.now[:alert] = "Could not interpret feed! Are you sure you have the correct URL?"
      render :new
      return
    end
    if @subscription.save
      redirect_to user_subscriptions_url(current_user)
    else
      flash.now[:alert] = @subscription.errors.full_messages.map { |message| message }.join("<p>")
      @categories = current_user.categories
      render :new
    end
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_collected_entries.html.erb
<div class="row">
<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
  <br>
  <% if entries.empty? %>
  <div class="well">
    <p class="text-center"><strong><em>No unread entries at this time</em></strong></p>
  </div>
  <% end %>
  <% entries.each do |entry| %>
    <div class="well" id="entry-well-<%= entry.id %>">
    <h4><%= link_to entry.title, entry.url %></h4>
    <% unless entry.author.nil? %>
    <p class="entry-author"><span class="glyphicon glyphicon-user"></span> <%= entry.author.html_safe %></p>
    <% end %>
    <p class="entry-timestamp"><span class="glyphicon glyphicon-time"></span> <%= entry.datetime.to_formatted_s(:superscription_custom) %></p>
    <% if show_subscription %>
      <p class="entry-subscription"><span class="glyphicon glyphicon-book"></span> from <em><%= entry.subscription.title %></em></p>
    <% end %>
    <% unless entry.content.nil? %>
      <div class="entry-content" data-id="<%= entry.id %>">
        <%= entry.content.html_safe %>
      </div>
    <% else %>
      <div class="entry-description" data-id="<%= entry.id %>">
        <%= entry.description.html_safe %>
      </div>
    <% end %>
    <% if read_marking %>
        <br><%= button_to "Mark as Read ✔", api_readings_url, :data => {:id => entry.id}, :class => "mark-as-read" %>
    <% end %>
    </div>
  <% end %>
</div>
</div>

app/views/subscriptions/edit.html.erb
<!-- ISSUE! This form should actually edit user_subscription info, not that of a subscription itself -->
<h3>Edit subscription</h3>
<form action="<%= subscriptions_url %>" method="post" accept-charset="utf-8">
  <input type="hidden"
  			 name="authenticity_token"
  			 value="<%= form_authenticity_token %>">
  <label for="new_subscription_url"><strong>URL<strong></label><br>
  <p>
    <input type="text" name="subscription[url]" value="<%= @subscription.url %>" id="new_subscription_url">
  </p>

  <select name="subscription[user_subscriptions_attributes][][category_id]" id="subscription_category">
    <% @categories.each do |category| %>
      <option value="<%= category.id %>" <%= @subscription.category == category ? 'selected' : '' %> ><%= category.name %></option>
    <% end %>
  </select>

  <p><input type="submit" value="Edit Subscription &rarr;"></p>
</form>

app/views/subscriptions/index.html.erb
<h3>My Subscriptions</h3>
<ul>
<% @user_subscriptions.each do |user_subscription|  %>
  <li id="user-subscription-item-<%= user_subscription.id%>"><em><%= link_to user_subscription.title, subscription_url(user_subscription.subscription.id) %></em>
    <% if user_subscription.category %>
     in category <%= link_to user_subscription.category.name, "/read#_#{user_subscription.category.name.downcase.gsub(" ", "_")}" %>
    <% end %>
    &mdash; <a href="#" class="delete-user-subscription" data-id="<%= user_subscription.id%>"><span class="glyphicon glyphicon-trash"></span></a>
  </li>
<% end %>
</ul>

<p><%= link_to "Create a new subscription!", new_user_subscription_url %></p>
<p><%= link_to "Manage categories!", categories_url %></p>

app/views/subscriptions/main.html.erb
<h3>Read stuff!</h3>

<ul class="nav nav-tabs" id="subscription-tabs">
  <% @categories.each do |category| %>
  <li><a href="#<%= category.name.downcase.gsub(" ", "_") %>" data-toggle="tab"><%= category.name %></a></li>
  <% end %>
</ul>

<div class="tab-content">
  <% @category_entries.each_with_index do |(name, entries), index| %>
    <div class="tab-pane" id="<%= name.downcase.gsub(" ", "_") %>">
      <%= render "collected_entries", :entries => entries, :read_marking => true, :show_subscription => true %>
    </div>
  <% end %>
</div>

app/views/subscriptions/new.html.erb
<h3>Create a new subscription!</h3>
<form action="<%= subscriptions_url %>" method="post" accept-charset="utf-8">
  <input type="hidden"
  			 name="authenticity_token"
  			 value="<%= form_authenticity_token %>">
  <label for="new_subscription_url"><strong>URL</strong></label><br>
  <p>
    <input type="text" name="subscription[url]" value="<%= @subscription.url %>" id="new_subscription_url">
  </p>

 <label for="subscription_category"><strong>Category</strong></label><br>
  <p>
    <select name="subscription[user_subscriptions_attributes][][category_id]" id="subscription_category">
      <% @categories.each do |category| %>
        <option value="<%= category.id %>"><%= category.name %></option>
      <% end %>
    </select>
  </p>

  <p><input type="submit" value="Create Subscription &rarr;"></p>
</form>

app/views/subscriptions/show.html.erb
<h3>Read all entries from <em><%= @subscription.title %></em></h3>
<%= render "collected_entries", :entries => @entries, :read_marking => false, :show_subscription => false %>