config/routes.rb
Superscription::Application.routes.draw do

  root :to => "static_pages#home"

  get :read, :to => "subscriptions#main"

  devise_for :users
  post :guest, :to => "guest_users#create"

  resources :users, :only => [] do
    resources :subscriptions, :only => [:index, :new]
  end

  resources :subscriptions, :only => [:create, :show]

  get :categories, :to => "categories#manage"

  namespace "api", :defaults => { :format => :json } do
    resources :user_subscriptions, :only => [:destroy]
    post "/user_subscriptions/:id/change_category", :to => "user_subscriptions#change_category"
    resources :readings, :only => [:create]
    resources :categories, :only => [:create, :destroy]
  end

end

app/views/layouts/_footer.html.erb
<hr>
<small><strong>Superscription</strong> by <strong><a href="http://zackmdavis.net">Zack M. Davis</a></strong> &bull;
  <%= link_to "Source", "https://github.com/zackmdavis/Superscription" %> &bull; free software under the <%= link_to "MIT License", "http://opensource.org/licenses/MIT" %>
  <br>
  <br>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="superscription-brand">Superscription</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav superscription-nav-button-group">
        <% if current_user %>
          <li><%= button_to "Read!", read_url, :method => :get, :id => :read_button %></li>
          <li><%= button_to "My Subscriptions", user_subscriptions_url(current_user.id), :method => :get %></li>
          <li><%= button_to "Sign out", destroy_user_session_url, :method => :delete %></li>
          <% else %>
          <li><%= button_to "Sign up", new_user_registration_url, :method => :get %></li>
          <li><%= button_to "Sign in", new_user_session_url, :method => :get  %></li>
          <li><%= button_to "Sign in as Guest", guest_url, :method => :post %></li>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-left">
      <p style="color: #DDDDDD; margin-top: 20px; margin-left: 10px">
            <% if current_user %>
              <strong><%= current_user.username %></strong> <a href="/users/edit"><span class="glyphicon glyphicon-edit"></span></a>
            <% else %>
              not logged in
            <% end %>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superscription</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Jim+Nightshade' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%= render "layouts/header" %>

  <div class="container">
    <div class="span10 offset1">
      <% if flash[:notice] %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>

      <%= render "layouts/footer" %>
    </div>
  </div>

</body>
</html>